### ISSUE TITLE
Internal server error (500) when I try to see the source code

### ISSUE THREAD

**Issue by sgoifo** [aurora-is-near/blockscout#6]
I can not access the source code page on your block explorer, I get an Internal server error.

You can see this error following this URL: https://explorer.mainnet.aurora.dev/address/0x9708e0C18B182dd11CdB186bCd5851838B133f30/contracts

Or by pressing the "Code" button at any contract:

![image](https://user-images.githubusercontent.com/45824980/151872247-77d48d14-5218-4d27-839c-e7ebec87d287.png)

Thank you very much

**Comment by pustovalov** [comment]
It looks like the problem is no longer relevant, please reopen if it will reoccur.

![image](https://github.com/aurora-is-near/blockscout/assets/1568885/10dd1a9a-7bb0-4181-b1ff-acf5dd85d498)
